#ifdef _WIN64
#pragma comment(linker, "/export:_dbg_addrinfoget=x64dbg._dbg_addrinfoget")
#pragma comment(linker, "/export:_dbg_addrinfoget=x64dbg._dbg_addrinfoget")
#pragma comment(linker, "/export:_dbg_addrinfoset=x64dbg._dbg_addrinfoset")
#pragma comment(linker, "/export:_dbg_bpgettypeat=x64dbg._dbg_bpgettypeat")
#pragma comment(linker, "/export:_dbg_dbgcmddirectexec=x64dbg._dbg_dbgcmddirectexec")
#pragma comment(linker, "/export:_dbg_dbgcmdexec=x64dbg._dbg_dbgcmdexec")
#pragma comment(linker, "/export:_dbg_dbgexitsignal=x64dbg._dbg_dbgexitsignal")
#pragma comment(linker, "/export:_dbg_dbginit=x64dbg._dbg_dbginit")
#pragma comment(linker, "/export:_dbg_functionoverlaps=x64dbg._dbg_functionoverlaps")
#pragma comment(linker, "/export:_dbg_getbplist=x64dbg._dbg_getbplist")
#pragma comment(linker, "/export:_dbg_getbranchdestination=x64dbg._dbg_getbranchdestination")
#pragma comment(linker, "/export:_dbg_getregdump=x64dbg._dbg_getregdump")
#pragma comment(linker, "/export:_dbg_isdebugging=x64dbg._dbg_isdebugging")
#pragma comment(linker, "/export:_dbg_isjumpgoingtoexecute=x64dbg._dbg_isjumpgoingtoexecute")
#pragma comment(linker, "/export:_dbg_memfindbaseaddr=x64dbg._dbg_memfindbaseaddr")
#pragma comment(linker, "/export:_dbg_memisvalidreadptr=x64dbg._dbg_memisvalidreadptr")
#pragma comment(linker, "/export:_dbg_memmap=x64dbg._dbg_memmap")
#pragma comment(linker, "/export:_dbg_memread=x64dbg._dbg_memread")
#pragma comment(linker, "/export:_dbg_memwrite=x64dbg._dbg_memwrite")
#pragma comment(linker, "/export:_dbg_sendmessage=x64dbg._dbg_sendmessage")
#pragma comment(linker, "/export:_dbg_valfromstring=x64dbg._dbg_valfromstring")
#pragma comment(linker, "/export:_dbg_valtostring=x64dbg._dbg_valtostring")
#pragma comment(linker, "/export:_plugin_debugpause=x64dbg._plugin_debugpause")
#pragma comment(linker, "/export:_plugin_debugskipexceptions=x64dbg._plugin_debugskipexceptions")
#pragma comment(linker, "/export:_plugin_logprintf=x64dbg._plugin_logprintf")
#pragma comment(linker, "/export:_plugin_logputs=x64dbg._plugin_logputs")
#pragma comment(linker, "/export:_plugin_menuadd=x64dbg._plugin_menuadd")
#pragma comment(linker, "/export:_plugin_menuaddentry=x64dbg._plugin_menuaddentry")
#pragma comment(linker, "/export:_plugin_menuaddseparator=x64dbg._plugin_menuaddseparator")
#pragma comment(linker, "/export:_plugin_menuclear=x64dbg._plugin_menuclear")
#pragma comment(linker, "/export:_plugin_registercallback=x64dbg._plugin_registercallback")
#pragma comment(linker, "/export:_plugin_registercommand=x64dbg._plugin_registercommand")
#pragma comment(linker, "/export:_plugin_unregistercallback=x64dbg._plugin_unregistercallback")
#pragma comment(linker, "/export:_plugin_unregistercommand=x64dbg._plugin_unregistercommand")
#else //x86
#pragma comment(linker, "/export:__dbg_addrinfoget=x32dbg._dbg_addrinfoget")
#pragma comment(linker, "/export:__dbg_addrinfoset=x32dbg._dbg_addrinfoset")
#pragma comment(linker, "/export:__dbg_bpgettypeat=x32dbg._dbg_bpgettypeat")
#pragma comment(linker, "/export:__dbg_dbgcmddirectexec=x32dbg._dbg_dbgcmddirectexec")
#pragma comment(linker, "/export:__dbg_dbgcmdexec=x32dbg._dbg_dbgcmdexec")
#pragma comment(linker, "/export:__dbg_dbgexitsignal=x32dbg._dbg_dbgexitsignal")
#pragma comment(linker, "/export:__dbg_dbginit=x32dbg._dbg_dbginit")
#pragma comment(linker, "/export:__dbg_functionoverlaps=x32dbg._dbg_functionoverlaps")
#pragma comment(linker, "/export:__dbg_getbplist=x32dbg._dbg_getbplist")
#pragma comment(linker, "/export:__dbg_getbranchdestination=x32dbg._dbg_getbranchdestination")
#pragma comment(linker, "/export:__dbg_getregdump=x32dbg._dbg_getregdump")
#pragma comment(linker, "/export:__dbg_isdebugging=x32dbg._dbg_isdebugging")
#pragma comment(linker, "/export:__dbg_isjumpgoingtoexecute=x32dbg._dbg_isjumpgoingtoexecute")
#pragma comment(linker, "/export:__dbg_memfindbaseaddr=x32dbg._dbg_memfindbaseaddr")
#pragma comment(linker, "/export:__dbg_memisvalidreadptr=x32dbg._dbg_memisvalidreadptr")
#pragma comment(linker, "/export:__dbg_memmap=x32dbg._dbg_memmap")
#pragma comment(linker, "/export:__dbg_memread=x32dbg._dbg_memread")
#pragma comment(linker, "/export:__dbg_memwrite=x32dbg._dbg_memwrite")
#pragma comment(linker, "/export:__dbg_sendmessage=x32dbg._dbg_sendmessage")
#pragma comment(linker, "/export:__dbg_valfromstring=x32dbg._dbg_valfromstring")
#pragma comment(linker, "/export:__dbg_valtostring=x32dbg._dbg_valtostring")
#pragma comment(linker, "/export:__plugin_debugpause=x32dbg._plugin_debugpause")
#pragma comment(linker, "/export:__plugin_debugskipexceptions=x32dbg._plugin_debugskipexceptions")
#pragma comment(linker, "/export:__plugin_logprintf=x32dbg._plugin_logprintf")
#pragma comment(linker, "/export:__plugin_logputs=x32dbg._plugin_logputs")
#pragma comment(linker, "/export:__plugin_menuadd=x32dbg._plugin_menuadd")
#pragma comment(linker, "/export:__plugin_menuaddentry=x32dbg._plugin_menuaddentry")
#pragma comment(linker, "/export:__plugin_menuaddseparator=x32dbg._plugin_menuaddseparator")
#pragma comment(linker, "/export:__plugin_menuclear=x32dbg._plugin_menuclear")
#pragma comment(linker, "/export:__plugin_registercallback=x32dbg._plugin_registercallback")
#pragma comment(linker, "/export:__plugin_registercommand=x32dbg._plugin_registercommand")
#pragma comment(linker, "/export:__plugin_unregistercallback=x32dbg._plugin_unregistercallback")
#pragma comment(linker, "/export:__plugin_unregistercommand=x32dbg._plugin_unregistercommand")
#endif //_WIN64

int test()
{
    return 0;
}